version: "3.8"

services:
  mongo:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db
        - mongodb_config:/data/configdb
      networks: 
        - myNetwork
      container_name: mongo

networks:
  myNetwork:
    driver: bridge

volumes:
  mongo:
  mongodb:
  mongodb_config: